# PostgreSQL. Versions 8.2 and up are supported.

development:
  adapter: postgresql
  encoding: unicode
  database: cultivate_london_development
  pool: 5
  username: vagrant
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: cultivate_london_test
  pool: 5
  username: vagrant
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cultivate_london_production
  pool: 5
  username: cultivate_london
  password:
